"""adicionar senha hash aos clientes

Revision ID: 50386a7a2a8f
Revises: cef411190026
Create Date: 2026-09-21 20:59:52.325498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50386a7a2a8f'
down_revision: Union[str, Sequence[str], None] = 'cef411190026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'clientes',
        sa.Column('senha_hash', sa.String(), nullable=True)
    )

    op.execute(
        "UPDATE clientes SET senha_hash = 'SEM_SENHA' WHERE senha_hash IS NULL"
    )

    op.alter_column(
        'clientes',
        'senha_hash',
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'senha_hash')
    # ### end Alembic commands ###
